#!/usr/bin/env python

# Merge RIR and Maxmind ASN data

# NOTE: This doesn't check to see if the command-line args are
# correct.

import sys

asn = {}

with open(sys.argv[1]) as rir:
     for line in rir:
          (asno, nic, country) = line.strip().split("|")
          if asno not in asn:
               asn[asno] = {}
          asn[asno]["nic"] = nic
          asn[asno]["country"] = country


with open(sys.argv[2]) as maxmind:
     for line in maxmind:
          (asno, org) = line.strip().split("|")
          if asno not in asn:
               asn[asno] = {}
          asn[asno]["org"] = org


for asno in asn:
     record = asn[asno]
     print "%s|%s|%s|%s" % (
          asno,
          record.get("nic", ""),
          record.get("country", ""),
          record.get("org", "")
          )
